{{- if and .Values.openstack.enabled .Values.openstack.csiCinder.enabled }}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: {{ include "cluster-addons.componentName" (list . "csi-cinder") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "csi-cinder") | nindent 4 }}
  annotations:
    # Tell Argo to ignore the non-controller owner references for this object
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true"
spec:
  repoURL: {{ .Values.openstack.csiCinder.chart.repo }}
  chartName: {{ .Values.openstack.csiCinder.chart.name }}
  version: {{ .Values.openstack.csiCinder.chart.version }}
  namespace: {{ .Values.openstack.targetNamespace }}
  releaseName: csi-cinder
  clusterSelector:
    matchLabels:
      capi.stackhpc.com/cluster: {{ include "cluster-addons.clusterName" . }}
  valuesTemplate: |
    csi:
      plugin:
        # This has to be non-empty or the chart fails to render
        volumes:
          - name: cacert
            emptyDir: {}
        volumeMounts:
          - name: cloud-config
            mountPath: /etc/config
            readOnly: true
          - name: cloud-config
            mountPath: /etc/kubernetes
            readOnly: true
    secret:
      enabled: true
      create: false
      name: cloud-config
    clusterID: {{ include "cluster-addons.clusterName" . }}
    storageClass:
      enabled: false
    {{- if or .Values.openstack.csiCinder.defaultStorageClass.enabled .Values.openstack.csiCinder.additionalStorageClasses }}
      custom: |-
      {{- with .Values.openstack.csiCinder.defaultStorageClass }}
        ---
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: {{ .name }}
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
        provisioner: cinder.csi.openstack.org
        parameters:
          availability: {{ .availabilityZone }}
          {{- with .volumeType }}
          type: {{ . }}
          {{- end }}
          {{- with .fstype }}
          fstype: {{ . }}
          {{- end }}
        reclaimPolicy: {{ .reclaimPolicy }}
        allowVolumeExpansion: {{ .allowVolumeExpansion }}
        volumeBindingMode: {{ .volumeBindingMode }}
        {{- with .allowedTopologies }}
        allowedTopologies: {{ toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
      {{- range $rangeItem := .Values.openstack.csiCinder.additionalStorageClasses }}
        ---
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: {{ $rangeItem.name }}
        provisioner: cinder.csi.openstack.org
        parameters:
          availability: {{ $rangeItem.availabilityZone }}
          {{- with $rangeItem.volumeType }}
          type: {{ . }}
          {{- end }}
          {{- with $rangeItem.fstype }}
          fstype: {{ . }}
          {{- end }}
        reclaimPolicy: {{ $rangeItem.reclaimPolicy }}
        allowVolumeExpansion: {{ $rangeItem.allowVolumeExpansion }}
        volumeBindingMode: {{ $rangeItem.volumeBindingMode }}
        {{- with $rangeItem.allowedTopologies }}
        allowedTopologies: {{ toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}